### ISSUE TITLE
Error: Not authenticated

### ISSUE THREAD

**Issue by olliedean** [abalabahaha/eris#1056]
The bot works completely fine, until all the shards start shitting out with this error:
```
data:    index.js:252374 - [13:44:18] Cluster 0 | Shard 0 | Error: Not authenticated
data:    index.js:252374 -     at Shard._onWSClose (/var/lucid/bot/node_modules/eris-sharder/node_modules/eris/lib/gateway/Shard.js:1877:23)
data:    index.js:252374 -     at WebSocket.emit (events.js:314:20)
data:    index.js:252374 -     at WebSocket.emitClose (/var/lucid/bot/node_modules/ws/lib/websocket.js:191:10)
data:    index.js:252374 -     at TLSSocket.socketOnClose (/var/lucid/bot/node_modules/ws/lib/websocket.js:858:15)
data:    index.js:252374 -     at TLSSocket.emit (events.js:326:22)
data:    index.js:252374 -     at net.js:672:12
data:    index.js:252374 -     at TCP.done (_tls_wrap.js:563:7)
data:    index.js:252374 - [13:44:18] Cluster 0 | Shard 0 disconnected!
data:    index.js:252374 - [13:44:48] Cluster 0 | Shard 0 established connection!
```
over and over again, until I restart. I have talked to discordware developers since I am running eris-sharder, and they say its an issue with Eris.

**Comment by ghost** [comment]
#967 is relevant here

**Comment by PassTheMayo** [comment]
I'm currently having this issue, but it only occurs when I use `getAllUsers` in the client settings. Turning it off will fix the issue, but doing so will break other features within my bot.

**Comment by abalabahaha** [comment]
Unfortunately we can't fix this unless someone comes up with a solid way to reproduce this without eris-sharder
