### ISSUE TITLE
message.removeReaction is not a function

### ISSUE THREAD

**Issue by ProfessorVarox** [abalabahaha/eris#1131]
Hello, I'm trying to make a reaction panel where you can react and the bot runs a specific action.

After the user reacted his reaction should be removed but the bot always throws an error when I try to remove the reaction

Error Code:
```
TypeError: message.removeReaction is not a function
    at Client.<anonymous> (D:\Discord_Bots\status4you\main.js:59:25)
    at Client.emit (events.js:314:20)
    at Shard.emit (D:\Discord_Bots\status4you\node_modules\eris\lib\gateway\Shard.js:239:26)
    at Shard.wsEvent (D:\Discord_Bots\status4you\node_modules\eris\lib\gateway\Shard.js:951:22)
    at Shard.onPacket (D:\Discord_Bots\status4you\node_modules\eris\lib\gateway\Shard.js:398:26)
    at Shard._onWSMessage (D:\Discord_Bots\status4you\node_modules\eris\lib\gateway\Shard.js:2134:29)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (D:\Discord_Bots\status4you\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:314:20)
```

Code snippet:
```
bot.on("messageReactionAdd", (message,emoji,reactor) => {
        var today = new Date();
        var dd = String(today.getDate()).padStart(2, '0');
        var mm = String(today.getMonth() + 1).padStart(2, '0');
        var yyyy = today.getFullYear();
        const date = dd + "-" + mm + "-" + yyyy

        switch (emoji.name) {
            case "➕" :
                const datReg = statDB.has(date)
                if (datReg) {
                    const oldStats = statDB.get(date,"success")
                    const newStats = Number(oldStats) + 1
                    statDB.set(date,Number(newStats),"success")
                }
                else {
                    const data = {
                        "success" : 1
                    }
                    statDB.set(date,data)
                }
                message.removeReaction(emoji.name,reactor.id)
                break
            case "🐛" :
                const datRegg = statDB.has(date)
                if (datRegg) {
                    const oldStats = statDB.get(date,"failed")
                    const newStats = Number(oldStats) + 1
                    statDB.set(date,Number(newStats),"failed")
                }
                else {
                    const data = {
                        "failed" : 1
                    }
                    statDB.set(date,data)
                }
               message.removeReaction(emoji.name,reactor.id)
        }
})
```

Node Version: v12.19.0
NPM Version: 6.14.11
Eris Version: 0.14.0

This is my first bot with Eris, I was using discord.js before

**Comment by ProfessorVarox** [comment]
Solved. I needed to cache the message
