### ISSUE TITLE
zlib error

### ISSUE THREAD

**Issue by retouching** [abalabahaha/eris#1144]
Hello !

I have a problem with eris and zlib. Sometimes, zlib throw an error with "Error: zlib error -3: data error". I would like to know why this problem happend. 

Error :
```
0|Akame Bo | Error: zlib error -3: data error
0|Akame Bo |     at Shard._onWSMessage (/opt/Akame Bot Discord/node_modules/eris/lib/gateway/Shard.js:2118:44)
0|Akame Bo |     at WebSocket.emit (events.js:315:20)
0|Akame Bo |     at Receiver.receiverOnMessage (/opt/Akame Bot Discord/node_modules/ws/lib/websocket.js:825:20)
0|Akame Bo |     at Receiver.emit (events.js:315:20)
0|Akame Bo |     at Receiver.dataMessage (/opt/Akame Bot Discord/node_modules/ws/lib/receiver.js:428:14)
0|Akame Bo |     at Receiver.getData (/opt/Akame Bot Discord/node_modules/ws/lib/receiver.js:367:17)
0|Akame Bo |     at Receiver.startLoop (/opt/Akame Bot Discord/node_modules/ws/lib/receiver.js:143:22)
0|Akame Bo |     at Receiver._write (/opt/Akame Bot Discord/node_modules/ws/lib/receiver.js:78:10)
0|Akame Bo |     at writeOrBuffer (internal/streams/writable.js:358:12)
0|Akame Bo |     at Receiver.Writable.write (internal/streams/writable.js:303:10)
0|Akame Bo |     at TLSSocket.socketOnData (/opt/Akame Bot Discord/node_modules/ws/lib/websocket.js:900:35)
0|Akame Bo |     at TLSSocket.emit (events.js:315:20)
0|Akame Bo |     at addChunk (internal/streams/readable.js:309:12)
0|Akame Bo |     at readableAddChunk (internal/streams/readable.js:284:9)
0|Akame Bo |     at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
0|Akame Bo |     at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
```

and my deps (include eris)

```js
"dependencies": {
  "eris": "^0.14.0",
  "erlpack": "^0.1.3",
  "ioredis": "^4.19.4",
  "moment": "^2.29.1",
  "mongoose": "^5.11.19",
  "promise.any": "^2.0.2",
  "winston": "^3.3.3",
  "zlib-sync": "^0.1.7"
}
```

**Comment by abalabahaha** [comment]
There have been a couple fixes since 0.14.0, does this still happen on 0.15.0? Are there any reconnects/connection issues around when this happens?

**Comment by someone508** [comment]
Yes, in my case it shows that error twice and then this
```
Error: Not authenticated
  at Shard._onWSClose (/app/node_modules/eris/lib/gateway/Shard.js:2100:23)
  at WebSocket.emit (events.js:315:20)
  at WebSocket.emitClose (/app/node_modules/ws/lib/websocket.js:198:10)
  at TLSSocket.socketOnClose (/app/node_modules/ws/lib/websocket.js:896:15)
  at TLSSocket.emit (events.js:327:22)
  at net.js:673:12
  at TCP.done (_tls_wrap.js:563:7) {
  code: 4003
}
```
I'm using v0.15.0, but this error doesn't happen often. Also there aren't any reconnect issues when this happens.

**Comment by LolRiTTeR** [comment]
I had the same error on the old InviteManager sourcecode ( https://github.com/SideProjectGuys/invite-manager-bot ) which used earlier eris versions.
It also happened a few minutes ago on our updated code ( https://github.com/LolRiTTeR/invite-manager-bot ) which is using eris v0.15.0

```
DISCORD DISCONNECT
DISCORD ERROR: Error: zlib error -3: data error
    at Shard._onWSMessage (/home/invman/regular-new/node_modules/eris/lib/gateway/Shard.js:2166:44)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at Receiver.receiverOnMessage (/home/invman/regular-new/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.EventEmitter.emit (domain.js:483:12)
    at Receiver.dataMessage (/home/invman/regular-new/node_modules/ws/lib/receiver.js:428:14)
    at Receiver.getData (/home/invman/regular-new/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/invman/regular-new/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/invman/regular-new/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.socketOnData (/home/invman/regular-new/node_modules/ws/lib/websocket.js:900:35)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
DISCORD CONNECT
DISCORD ERROR: Error: zlib error -3: data error
    at Shard._onWSMessage (/home/invman/regular-new/node_modules/eris/lib/gateway/Shard.js:2166:44)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at Receiver.receiverOnMessage (/home/invman/regular-new/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.EventEmitter.emit (domain.js:483:12)
    at Receiver.dataMessage (/home/invman/regular-new/node_modules/ws/lib/receiver.js:428:14)
    at Receiver.getData (/home/invman/regular-new/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/invman/regular-new/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/invman/regular-new/node_modules/ws/lib/receiver.js:78:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.socketOnData (/home/invman/regular-new/node_modules/ws/lib/websocket.js:900:35)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
syncDB: 1.737ms
DISCORD ERROR: Error: Connection timeout
    at Timeout.<anonymous> (/home/invman/regular-new/node_modules/eris/lib/gateway/Shard.js:367:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
DISCORD DISCONNECT
DISCORD CONNECT
```

//Edit: As someone508 mentioned, this error does not happen very often.
