### ISSUE TITLE
Constants.Permissions can no longer be used with createChannel permissionOverwrites option

### ISSUE THREAD

**Issue by eritbh** [abalabahaha/eris#1196]
Since `Constants.Permissions` was converted to bigints with 0.15, passing those values as the values of permission overwrites when creating a channel no longer works:

```js
guild.createChannel('something', 0, {
  permissionOverwrites: [
    {
      id: guild.id,
      type: 0, // role overwrite
      deny: Eris.Constants.Permissions.viewChannel,
    },
  ],
});
```

Error thrown:

```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at actualCall (node_modules/eris/lib/rest/RequestHandler.js:153:41)
    at SequentialBucket.check (node_modules/eris/lib/util/SequentialBucket.js:56:28)
    at SequentialBucket.queue (node_modules/eris/lib/util/SequentialBucket.js:75:14)
    at node_modules/eris/lib/rest/RequestHandler.js:392:40
    at new Promise (<anonymous>)
    at RequestHandler.request (node_modules/eris/lib/rest/RequestHandler.js:78:16)
    at Client.createChannel (node_modules/eris/lib/Client.js:433:36)
    at Guild.createChannel (node_modules/eris/lib/structures/Guild.js:350:43)
    at (my code)
```

Seems the solution would be to pass a replacer function to [this `JSON.stringify` call](https://github.com/abalabahaha/eris/blob/69f812c43cd8d9591d2ca455f7c8b672267a2ff6/lib/rest/RequestHandler.js#L152) to render bigints as strings in JSON to make Discord happy. By doing it there instead of in `createChannel` itself, any future bigint fields will be serialized the same way as well.

**Comment by abalabahaha** [comment]
Fixed in 0.16.0
