### ISSUE TITLE
Somewhat frequent Error 1001 / shard._onWSClose ?

### ISSUE THREAD

**Issue by zfbx** [abalabahaha/eris#1270]
For some reason I get an error like this fairly common
```
Error: Error: 1001: 
   at Shard._onWSClose (/home/..../eris/lib/gateway/Shard.js:2094:51)
   at WebSocket.emit (events.js:210:5)
   at WebSocket.emitClose (/home/..../ws/lib/websocket.js:198:10)
   at TLSSocket.socketOnClose (/home/..../ws/lib/websocket.js:894:15)
   at TLSSocket.emit (events.js:215:7)
   at net.js:658:12
   at TCP.done (_tls_wrap.js:481:7)
```
Is this common? I'm mostly used to d.js ~~but this system uses an older version of node and they dropped support.~~
It's running on an actual server with a stable connection afaik but quite often it'll throw that error than retrigger the ready event. I'm using it fairly barebones with just the main client (no command handler) and listeners for ready, error and messageCreate.

**Comment by bsian03** [comment]
Please refer to the Discord developers documentation on gateway close codes.
