### ISSUE TITLE
TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by ghost** [abalabahaha/eris#1284]
Error:
```
TypeError: Cannot read property 'add' of undefined
[1]     at new Guild (/usr/src/covid/node_modules/eris/lib/structures/Guild.js:133:78)
[1]     at Map.add (/usr/src/covid/node_modules/eris/lib/util/Collection.js:41:19)
[1]     at Shard.createGuild (/usr/src/covid/node_modules/eris/lib/gateway/Shard.js:1646:42)
[1]     at Shard.wsEvent (/usr/src/covid/node_modules/eris/lib/gateway/Shard.js:757:40)
[1]     at Shard.onPacket (/usr/src/covid/node_modules/eris/lib/gateway/Shard.js:1922:26)
[1]     at Shard._onWSMessage (/usr/src/covid/node_modules/eris/lib/gateway/Shard.js:1793:29)
[1]     at WebSocket.emit (events.js:314:20)
[1]     at Receiver.receiverOnMessage (/usr/src/covid/node_modules/ws/lib/websocket.js:873:20)
[1]     at Receiver.emit (events.js:314:20)
[1]     at Receiver.dataMessage (/usr/src/covid/node_modules/ws/lib/receiver.js:517:14)
[1]     at Receiver.getData (/usr/src/covid/node_modules/ws/lib/receiver.js:435:17)
[1]     at Receiver.startLoop (/usr/src/covid/node_modules/ws/lib/receiver.js:143:22)
[1]     at Receiver._write (/usr/src/covid/node_modules/ws/lib/receiver.js:78:10)
[1]     at writeOrBuffer (_stream_writable.js:352:12)
[1]     at Receiver.Writable.write (_stream_writable.js:303:10)
[1]     at TLSSocket.socketOnData (/usr/src/covid/node_modules/ws/lib/websocket.js:948:35)
```

Happens when connecting, and the bot is connecting to multiple shards. Doesn't happen on all shards when they are connecting, but many when the bot has many guilds.
(probably fixed in dev, I don't know)

**Comment by DonovanDMC** [comment]
What version are you running here
nothing on line 133 of Guild.js uses an `add` method
> https://github.com/abalabahaha/eris/blob/master/lib/structures/Guild.js#L133
> client.channelGuildMap[channel.id] = this.id;

**Comment by abalabahaha** [comment]
Closing due to lack of detail and inactivity
