### ISSUE TITLE
Jump links from DM messages throw errors

### ISSUE THREAD

**Issue by Snazzah** [abalabahaha/eris#1347]
Getting the jump link for a DM message returns an error, presumably because the channel is actually partial without the library realizing.

```js
TypeError: Cannot read properties of undefined (reading 'id')
    at Message.get jumpLink [as jumpLink] (D:\GitHub\CraigChat\craig\node_modules\eris\lib\structures\Message.js:380:118)
    at Join.run (D:\GitHub\CraigChat\craig\bot\dist\commands\join.js:201:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SlashCreator._runCommand (D:\GitHub\CraigChat\craig\node_modules\slash-create\lib\creator.js:656:28)
```

**Comment by HeadTriXz** [comment]
Eris does check whether the channel is a DM channel. My guess is that Channel#type is undefined, meaning it would think it is a guild channel.

**Comment by DonovanDMC** [comment]
^ exactly this, Eris DOES check, dm channels just don't have a `type` property when they're partial
https://github.com/abalabahaha/eris/blob/90fad3a41dc81c699d8de33a65369380cfde69f2/lib/structures/Message.js#L379-L381

**Comment by Snazzah** [comment]
> presumably because the channel is actually partial without the library realizing.

Yeah, makes sense lol
