### ISSUE TITLE
Eris.Constants are undefined

### ISSUE THREAD

**Issue by radstevee** [abalabahaha/eris#1360]
My code: 
```
import fs from 'fs';
import Eris from 'eris';
const discordConfig = JSON.parse(fs.readFileSync("config/discord.json"));
const Constants = Eris.Constants;
var bot = new Eris(
    discordConfig.token, {
    intents: [
        "allNonPrivileged",
        "allPrivileged"
    ]
},
    {
        description: "",
        owner: discordConfig.owner,
        prefix: discordConfig.prefix
    }
);

bot.on('interactionCreate', async interaction => {
    if(interaction.author.bot || !interaction.content.startsWith(discordConfig.prefix)/* || !interaction instanceof Eris.CommandInteraction*/) return;
    let args = interaction.content.slice(discordConfig.prefix.length).split(/ +/);
    let command = args.shift().toLowerCase();
    console.log(command)
    bot.commands[command].run(message);
});


console.log(Constants)

bot.on("ready", () => {
    const logChannel = bot.getChannel(discordConfig.logChannel);
    console.log(`Logged in as: ${bot.user.username}`);
    logChannel.createMessage({
        embed: {
            title: "Bot Started",
            color: discordConfig.startColor,
            timestamp: new Date()
        }
    });
    bot.createCommand({
        name: "test",
        description: "Test command",
        type: Constants.ApplicationCommandTypes.MESSAGE
    });
});

bot.on("error", error => {
    console.log(error);
    bot.createMessage(discordConfig.logChannel, {
        embed: {
            title: "Error",
            description: String(error),
            color: "000",
        }
    });
})

function logDiscord(text) {
    bot.createMessage(discordConfig.logChannel, {
        embed: {
            title: "Log",
            description: String(text),
            color: "3113197",
        }
    });
}

bot.connect();

```

And it just says 
```
TypeError: Cannot read properties of undefined (reading 'ApplicationCommandTypes')
```

**Comment by ghost** [comment]
This is not the place to ask eris related questions. Use the [support server](https://discord.gg/eris) instead.

**Comment by eritbh** [comment]
When using CommonJS (i.e. `require()`), `Eris` can be used as both a function and to access other things like constants. With ES modules that isn't possible, so the way you import Eris has to change a bit. You need to use `import * as Eris from 'eris'`, and then instead of calling `new Eris(...)` to create your client you'll need to use `new Eris.Client(...)`.

**Comment by radstevee** [comment]
> 

Hello, yes but that just gives me this error:

```
/home/radsteve/node-dev/Spondulicks/node_modules/eris/lib/Client.js:567
        return this.requestHandler.request("POST", Endpoints.COMMANDS(this.application.id), true, command);
                                                                                       ^

TypeError: Cannot read properties of undefined (reading 'id')
    at Client.createCommand (/home/radsteve/node-dev/Spondulicks/node_modules/eris/lib/Client.js:567:88)
    at file:///home/radsteve/node-dev/Spondulicks/app.js:25:12

Node.js v17.9.0
```

**Comment by HeadTriXz** [comment]
> This is not the place to ask eris related questions. Use the [support server](https://discord.gg/eris) instead.

Like Linker mentioned before, use the [support server](https://discord.gg/eris) instead.
