### ISSUE TITLE
crashes on messages from clyde

### ISSUE THREAD

**Issue by DetachHead** [abalabahaha/eris#1449]
discord recently introduced an AI chatbot: https://support.discord.com/hc/en-us/articles/13066317497239-Clyde-Discord-s-AI-Chatbot

whenever it sends a message, eris crashes
```
[main] /app/node_modules/eris/lib/gateway/Shard.js:843
[main]                     packet.d.member.id = packet.d.user_id;
[main]                                        ^
[main] TypeError: Cannot set properties of undefined (setting 'id')
[main]     at Shard.wsEvent (/app/node_modules/eris/lib/gateway/Shard.js:843:40)
[main]     at Shard.onPacket (/app/node_modules/eris/lib/gateway/Shard.js:415:26)
[main]     at Shard._onWSMessage (/app/node_modules/eris/lib/gateway/Shard.js:2621:29)
[main]     at WebSocket.emit (node:events:513:28)
[main]     at Receiver.receiverOnMessage (/app/node_modules/eris/node_modules/ws/lib/websocket.js:1184:20)
[main]     at Receiver.emit (node:events:513:28)
[main]     at Receiver.dataMessage (/app/node_modules/eris/node_modules/ws/lib/receiver.js:541:14)
[main]     at Receiver.getData (/app/node_modules/eris/node_modules/ws/lib/receiver.js:459:17)
[main]     at Receiver.startLoop (/app/node_modules/eris/node_modules/ws/lib/receiver.js:158:22)
[main]     at Receiver._write (/app/node_modules/eris/node_modules/ws/lib/receiver.js:84:10)
[main]     at writeOrBuffer (node:internal/streams/writable:392:12)
[main]     at _write (node:internal/streams/writable:333:10)
[main]     at Receiver.Writable.write (node:internal/streams/writable:337:10)
[main]     at TLSSocket.socketOnData (/app/node_modules/eris/node_modules/ws/lib/websocket.js:1278:35)
[main]     at TLSSocket.emit (node:events:513:28)
[main]     at addChunk (node:internal/streams/readable:324:12)
```

**Comment by bsian03** [comment]
Clyde has been discontinued
