### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by old-df38257622** [abalabahaha/eris#1461]
Hello! When my bot runs for a while, it eventually crashes with a "Connection reset by peer" error.
```
node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: Connection reset by peer
    at Shard._onWSClose (C:\Users\letters\Projects\lettersbotnext\node_modules\eris\lib\gateway\Shard.js:2573:23)
    at WebSocket.emit (node:events:512:28)
    at WebSocket.emitClose (C:\Users\letters\Projects\lettersbotnext\node_modules\ws\lib\websocket.js:258:10)
    at Receiver.receiverOnFinish (C:\Users\letters\Projects\lettersbotnext\node_modules\ws\lib\websocket.js:1173:20)
    at Receiver.emit (node:events:512:28)
    at finish (node:internal/streams/writable:757:10)
    at node:internal/streams/writable:735:13
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on Client instance at:
    at Shard.emit (C:\Users\letters\Projects\lettersbotnext\node_modules\eris\lib\gateway\Shard.js:247:26)
    at Shard.disconnect (C:\Users\letters\Projects\lettersbotnext\node_modules\eris\lib\gateway\Shard.js:167:18)
    at Shard._onWSClose (C:\Users\letters\Projects\lettersbotnext\node_modules\eris\lib\gateway\Shard.js:2583:14)
    at WebSocket.emit (node:events:512:28)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 1006
}
```
The thing is, my internet is very consistent, I've run a bot with discord.js and discord.py before on this network and never experienced this issue, so I don't know what's going on here. I've seen people say to handle the error and continue on, but I'm not sure how to reconnect when this error occurs.

**Comment by DonovanDMC** [comment]
![image](https://github.com/abalabahaha/eris/assets/17226394/ab1f1194-4278-42db-8d44-ac7909de9291)
handle the error event

**Comment by old-df38257622** [comment]
That's... unhelpful, to put it lightly. I just explained that as far as I can tell, the bot is no longer connected by the time the error occurs, and I'm not sure what to do with the error. Sure, I have a try/catch. What should I have in the `try` clause? `bot.connect()`? Is that what's even causing the error? The stacktrace is unclear about that. How am I supposed to "handle" it?

**Comment by DonovanDMC** [comment]
It's an event
add a listener for it - congrats, it's handled

**Comment by old-df38257622** [comment]
For anyone finding this issue in the future, the trick seems to be:
```
process.on("uncaughtException", function (err) {
    console.error(err)
})
```

**Comment by DonovanDMC** [comment]
Or.. just.. literally add a listener for the `error` event
It's throwing an error explicitly because you don't have a listener for the event
