### ISSUE TITLE
undefined is not an object (evaluating 'this.application.id')

### ISSUE THREAD

**Issue by radstevee** [abalabahaha/eris#1463]
Hello, I'm getting the error `undefined is not an object (evaluating 'this.application.id')`, full log:
```
  theris-bot ❯❯❯ bun src/main.ts                                                                                                                                       
604 |                     throw new Error("Slash Command names must match the regular expression \"^[\\w-]{1,32}$\"");
605 |                 }
606 |             }
607 |         }
608 |         command.default_permission = command.defaultPermission;
609 |         return this.requestHandler.request("POST", Endpoints.COMMANDS(this.application.id), true, command);
                                                                         ^
TypeError: undefined is not an object (evaluating 'this.application.id')
      at createCommand (/home/radsteve/theris-bot/node_modules/eris/lib/Client.js:609:70)
      at register (/home/radsteve/theris-bot/src/command.ts:48:12)
      at /home/radsteve/theris-bot/src/main.ts:29:4
      at processTicksAndRejections (:55:76)
```

this is my command.ts:
```typescript
import Eris from "eris";

class TherisCommand {
    commandName: string;
    commandDescription: string;
    commandOptions: Eris.ApplicationCommandOptions[];
    commandType: 1 | 3 | 2;
    run: Function;
    client: Eris.Client;
    isGuildCommand: Boolean;
    guildId: number;


    constructor(commandName, commandDescription, commandOptions, commandType, run, client, isGuildCommand, guildId) {
        this.commandName = commandName;
        this.commandDescription = commandDescription;
        this.commandOptions = commandOptions;
        this.commandType = commandType;
        this.run = run;
        this.client = client;
        this.isGuildCommand = isGuildCommand;
        this.guildId = guildId;
    }

    runCommand(client, interaction, args) {
        this.run(client, interaction, args);
    }

    register() {
        if(this.isGuildCommand) {
            this.client.createGuildCommand(this.guildId.toString(), {
                name: this.commandName,
                description: this.commandDescription,
                options: this.commandOptions,
                type: this.commandType
            });
        } else {
            this.client.createCommand({
                name: this.commandName,
                description: this.commandDescription,
                options: this.commandOptions,
                type: this.commandType
            });
        }
    }
}

export default TherisCommand;
```

and I'm just creating a new Instance of that class and calling .register() (doesn't work with guilds & app commands).

I'm using TypeScript with Bun and Eris v0.17.2

**Comment by bsian03** [comment]
Your client must have received READY from discord before you can use that property

**Comment by radstevee** [comment]
> Your client must have received READY from discord before you can use that property

Ah true, I didnt run the code inside the on(ready) part. Thanks!
