### ISSUE TITLE
Using slash command auto complete in forums channels throw an error

### ISSUE THREAD

**Issue by flav-code** [abalabahaha/eris#1512]
```js
[CLUSTER 0] [bot_630329110388015104] [SHARD 0] has an Error ! Error: Missing object id
    at Collection.update (/dev-bot/node_modules/eris/lib/util/Collection.js:31:19)
    at new AutocompleteInteraction (/dev-bot/node_modules/eris/lib/structures/AutocompleteInteraction.js:47:45)
    at Interaction.from (/dev-bot/node_modules/eris/lib/structures/Interaction.js:43:24)
    at Shard.wsEvent (/dev-bot/node_modules/eris/lib/gateway/Shard.js:2685:60)
    at Shard.onPacket (/dev-bot/node_modules/eris/lib/gateway/Shard.js:415:26)
    at Shard._onWSMessage (/dev-bot/node_modules/eris/lib/gateway/Shard.js:2815:29)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at Receiver.receiverOnMessage (/dev-bot/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:519:28)
```

**Comment by bsian03** [comment]
This doesn't look like it's specific to forum channels or autocomplete interactions (although I haven't actually checked the payload for autocomplete interactions so can't confirm). However it does look like member `id` isn't sniped when either the channel/guild isn't cached.
@JustCat80 was there a specific reason why in your PR #1280 `id` is being sniped only if the channel contains a guild and not when it checks whether client contains the guild instead?

**Comment by JustCat80** [comment]
Honestly I don't remember, but it's not unlikely I forgot or added the member id line in later and never ran into an uncached guild during testing
