### ISSUE TITLE
VoiceConnection#playFile() crashes bot with 'TypeError: Bad argument'

### ISSUE THREAD

**Issue by Ratismal** [abalabahaha/eris#16]
Hi,

I've been trying to make a simple music bot with Eris for learning experience. The objective is to have it join a voice channel, play an existing song file, and leave. Joining and leaving the voice channel has been working, but whenever I attempt to play the song the bot crashes.

Here is the code that I'm executing:

``` javascript
voiceConnections[msg.channel.guild.id].playFile("file.mp3");
```

where voiceConnections is an object containing VoiceConnection objects mapped to guild IDs, and "file.mp3" is an existing mp3 file.

The bot then crashes with this message:

``` javascript
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at Object.exports.spawn (child_process.js:362:9)
    at VoiceConnection.playStream (c:\Users\user\WebstormProjects\pomfbot\node_modules\eris\lib\core\VoiceConnection.js:307:36)
    at VoiceConnection.playFile (c:\Users\user\WebstormProjects\pomfbot\node_modules\eris\lib\core\VoiceConnection.js:298:14)
    at Client.<anonymous> (c:\Users\user\WebstormProjects\pomfbot\pomf.js:83:56)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at Shard.wsEvent (c:\Users\user\WebstormProjects\pomfbot\node_modules\eris\lib\core\Shard.js:319:33)
    at WebSocket.<anonymous> (c:\Users\user\WebstormProjects\pomfbot\node_modules\eris\lib\core\Shard.js:953:34)
```

I know for sure that the issue isn't finding the file, because if I tell it to play a nonexisting file it crashes with an ENOENT error.

I have all the necessary libs, such as node-gyp, node-opus, and ffmpeg. I have installed Eris without the `--no-optional` tag. I will be more than happy to provide any additional information.

Thank you for your time,
Ratismal

**Comment by davidcole1340** [comment]
Seems like Eris is unable to find your `ffmpeg` or `avconv` executable, can you double check FFmpeg is working?

**Comment by Ratismal** [comment]
I'm fairly certain that ffmpeg is working, because I run [rhino music bot](https://github.com/SexualRhinoceros/MusicBot) that uses ffmpeg without issue. Here is the console output for when I run `ffmpeg`:
![console output](https://i.gyazo.com/d52fb23e151251db15bc28569de3f3d8.png)
Do I need both `ffmpeg` and `avconv` installed? The [docs](https://abal.moe/Eris/docs.html) have no mention of either.

**Comment by davidcole1340** [comment]
You only need one installed.

**Comment by devsnek** [comment]
@Ratismal --no-optional installs without optional things like voice

**Comment by davidcole1340** [comment]
@GusCaplan He said he installed Eris without the tag, it's worded weird, thought that as well.

**Comment by Ratismal** [comment]
> I have installed Eris **without** the --no-optional tag.

Sorry for the confusion.
