### ISSUE TITLE
TypeError: Cannot read property 'allow' of undefined

### ISSUE THREAD

**Issue by briantanner** [abalabahaha/eris#162]
```
2|Dyno     | TypeError: Cannot read property 'allow' of undefined
2|Dyno     |     at Client.editRole (/home/dyno/Dyno/node_modules/eris/lib/Client.js:612:100)
2|Dyno     |     at Role.edit (/home/dyno/Dyno/node_modules/eris/lib/structures/Role.js:61:49)
2|Dyno     |     at /home/dyno/Dyno/build/core/structures/Role.js:40:16
```

**Comment by abalabahaha** [comment]
Should be fixed in e3a9491

Also @hsiW this isn't voice-related
