### ISSUE TITLE
Error: closed before the connection is established

### ISSUE THREAD

**Issue by briantanner** [abalabahaha/eris#201]
Voice connection error when playing... `conn.on('error')`

```	
Error: closed before the connection is established
    at WebSocket.close (/home/dyno/Dyno/node_modules/ws/lib/WebSocket.js:270:28)
    at VoiceConnection.disconnect (/home/dyno/Dyno/node_modules/eris/lib/voice/VoiceConnection.js:352:25)
    at VoiceConnection.connect (/home/dyno/Dyno/node_modules/eris/lib/voice/VoiceConnection.js:154:18)
    at Timeout.setTimeout [as _onTimeout] (/home/dyno/Dyno/node_modules/eris/lib/voice/VoiceConnection.js:155:42)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)```

**Comment by abalabahaha** [comment]
You're attempting to join the voice channel multiple times in quick succession... Probably should try to avoid this on your end
