### ISSUE TITLE
opusscript error when creating a sharedStream

### ISSUE THREAD

**Issue by hsiW** [abalabahaha/eris#220]
New error as of this commit https://github.com/abalabahaha/eris/commit/7a153a1fc4a85a08becc7f22cb425f459be4f07c
```
TypeError: Cannot convert "undefined" to int
    at Object.toWireType (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/opusscript/build/opusscript_native.js:1:153537)
    at OpusScriptHandler$_encoder_ctl [as _encoder_ctl] (eval at new_ (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/opusscript/build/opusscript_native.js:1:174351), <anonymous>:9:26)
    at OpusScript.encoderCTL (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/opusscript/index.js:73:28)
    at SharedStream (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/eris/lib/voice/SharedStream.js:53:27)
    at Object.<anonymous> (/home/mei/Programming/Discord/Nagato/NagatoBot/commands/Music/listen.js:3:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)```

**Comment by abalabahaha** [comment]
Next time just reopen the old issue
