### ISSUE TITLE
Undefined content sent as 'undefined' string

### ISSUE THREAD

**Issue by hsiW** [abalabahaha/eris#227]
Passing `undefined` as an argument to `createMessage` results in the string 'undefined' being sent as the content of the message.

Code:

```javascript
msg.channel.createMessage()
```

Result: Message with content `'undefined'` is sent.

Expected result: Message fails to send with an error:
```json
{
  "code": 50006,
  "message": "Cannot send an empty message"
}
```

Only started to appear after https://github.com/abalabahaha/eris/commit/6b581058ea141cbfa6ad044e9a638ea6a0bc2bfa

**Comment by hsiW** [comment]
Still exists in https://github.com/abalabahaha/eris/commit/987cf320d37607bb04d42469edcbc1de128b80f1

**Comment by vladfrangu** [comment]
It is known this also appears for embed-only messages right?

**Comment by hsiW** [comment]
The original issue still exists in https://github.com/abalabahaha/eris/commit/2e0afd380a9d8cc37f324eae2d9f485ecf24875a but the issue where embeds would send the string `undefined` when there is no message content as been fixed.

**Comment by abalabahaha** [comment]
rip me

how about now

**Comment by hsiW** [comment]
Now theres an error on every message sent without content:
`
(node:14128) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property 'replace' of undefined
`
This includes anytime a message is sent with `undefined` as the content, including in embeds

**Comment by hsiW** [comment]
It was fixed in https://github.com/abalabahaha/eris/commit/2e0afd380a9d8cc37f324eae2d9f485ecf24875a but reverted in https://github.com/abalabahaha/eris/commit/b8799980cdb85e08b69392eb890826b2e897e9b5 seeing as it has to do with [this](https://github.com/abalabahaha/eris/blob/b8799980cdb85e08b69392eb890826b2e897e9b5/lib/Client.js#L892-L894)

**Comment by hsiW** [comment]
In https://github.com/abalabahaha/eris/commit/b8799980cdb85e08b69392eb890826b2e897e9b5 you are unable use `createMessage` at all with any content as it errors with:
```
Error: No content, file, or embed
    at Nagato.createMessage (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/eris/lib/Client.js:882:35)
    at GuildChannel.createMessage (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/eris/lib/structures/Channel.js:67:72)
    at eval (eval at process (/home/mei/Programming/Discord/Nagato/NagatoBot/commands/Admin/eval.js:17:22), <anonymous>:1:17)
    at Eval.process (/home/mei/Programming/Discord/Nagato/NagatoBot/commands/Admin/eval.js:17:22)
    at Nagato.MessageHandler.messageHandler (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/nagato/lib/MessageHandler.js:28:36)
    at emitOne (events.js:96:13)
    at Nagato.emit (events.js:189:7)
    at Shard.wsEvent (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/eris/lib/gateway/Shard.js:394:33)
    at WebSocket.ws.onmessage (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/eris/lib/gateway/Shard.js:1457:34)
    at WebSocket.onMessage (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/ws/lib/EventTarget.js:103:16)
```
[Relevant Lines](https://github.com/abalabahaha/eris/blob/b8799980cdb85e08b69392eb890826b2e897e9b5/lib/Client.js#L881-L883)

**Comment by Ratismal** [comment]
I am also getting this on b879998, when doing `msg.edit('content')`. Doing `msg.edit({content: 'content'})` works fine.

**Comment by Ratismal** [comment]
I have isolated the issue and fixed it in #230

**Comment by abalabahaha** [comment]
I think 141fc4e works this time

**Comment by Ratismal** [comment]
Seems to be working, thanks
