### ISSUE TITLE
USER_UPDATE error on editSelf with avatar

### ISSUE THREAD

**Issue by hsiW** [abalabahaha/eris#232]
Changing your avatar with `editSelf` returns the following error but also changes the avatar correctly:

```
TypeError: Cannot read property 'id' of undefined
    at Shard.wsEvent (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/eris/lib/gateway/Shard.js:1189:63)
    at WebSocket.ws.onmessage (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/eris/lib/gateway/Shard.js:1462:34)
    at WebSocket.onMessage (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/ws/lib/EventTarget.js:103:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:192:7)
    at Receiver._receiver.onmessage (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/ws/lib/WebSocket.js:146:54)
    at Receiver.dataMessage (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/home/mei/Programming/Discord/Nagato/NagatoBot/node_modules/ws/lib/WebSocket.js:142:22)
```

Code:

```js
setAvatar() {
        fs.readdir(`${__dirname}/../avatars/`, (err, files) => {
            if (err)
                this.bot.log.error(err);
            else {
                const avatar = files[Math.floor(Math.random() * (files.length))];
                fs.readFile(`${__dirname}/../avatars/${avatar}`, (error, image) => {
                    if (error)
                        this.bot.log.error(err);
                    else
                        this.bot.editSelf({
                            avatar: `data:image/jpg;base64,${image.toString('base64')}`
                        })
                        .then(() => this.bot.log.info('Successfully changed avatar.'))
                        .catch(e => this.bot.log.error('Avatar Error: ' + e));
                })
            }
        });
    }
```
This seems to be caused by the user getting a USER_UPDATE for themselves but the packet not containing a user key in the dispatch object.

```json
{
	"t": "USER_UPDATE",
	"s": 4,
	"op": 0,
	"d": {
		"verified": true,
		"username": "alex's alter ego",
		"mfa_enabled": true,
		"id": "285951325479632896",
		"email": null,
		"discriminator": "6717",
		"bot": true,
		"avatar": "c404a9e988d568ccd0be69a8594f63d8"
	}
}
```
vs
```json
{
	"t": "USER_UPDATE",
	"s": 4,
	"op": 0,
	"d": {
		"user": {
			"verified": true,
			"username": "alex's alter ego",
			"mfa_enabled": true,
			"id": "285951325479632896",
			"email": null,
			"discriminator": "6717",
			"bot": true,
			"avatar": "c404a9e988d568ccd0be69a8594f63d8"
		}
	}
}
```

This error has been around since https://github.com/abalabahaha/eris/commit/9d1ad7c67e980966d5f65e37d223b688f0caecf8 when it was changed how packets for user updates were handled

[Relevant Line](https://github.com/abalabahaha/eris/blob/dev/lib/gateway/Shard.js#L1189)

**Comment by abalabahaha** [comment]
Should be fixed in 6ab4019
