### ISSUE TITLE
Guild.banMember errors with invalid characters in header.

### ISSUE THREAD

**Issue by Ovyerus** [abalabahaha/eris#276]
This is the second time I've known this to happen, but it seems to be pretty rare.

```js
TypeError: The header content contains invalid characters
    at validateHeader (_http_outgoing.js:507:11)
    at ClientRequest.setHeader (_http_outgoing.js:511:3)
    at new ClientRequest (_http_client.js:171:14)
    at Object.request (http.js:39:10)
    at Object.request (https.js:233:15)
    at actualCall (/home/moo/knife-bot/node_modules/eris/lib/rest/RequestHandler.js:129:33)
    at SequentialBucket.check (/home/moo/knife-bot/node_modules/eris/lib/util/SequentialBucket.js:70:28)
    at SequentialBucket.queue (/home/moo/knife-bot/node_modules/eris/lib/util/SequentialBucket.js:38:14)
    at Promise (/home/moo/knife-bot/node_modules/eris/lib/rest/RequestHandler.js:281:40)
    at Promise._execute (/home/moo/knife-bot/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/moo/knife-bot/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/moo/knife-bot/node_modules/bluebird/js/release/promise.js:79:10)
    at RequestHandler.request (/home/moo/knife-bot/node_modules/eris/lib/rest/RequestHandler.js:60:16)
    at Client.banGuildMember (/home/moo/knife-bot/node_modules/eris/lib/Client.js:1262:36)
    at Guild.banMember (/home/moo/knife-bot/node_modules/eris/lib/structures/Guild.js:445:49)
    at softBanMember (/home/moo/knife-bot/src/commands/halfway/halfway.js:57:37)
```

**Comment by abalabahaha** [comment]
Are you URI encoding the reason field? Sounds like someone has unicode characters in their username.

**Comment by Ovyerus** [comment]
No I'm not, but the first time this happened to me, I'm pretty certain the person's name didn't have any funny unicode chars in their name, but the second time this happned, the user did. 

Also isn't that handled in the body content? Why would it raise an error about the header content? (I'm not 100% knowledgable about HTTP request formatting, so forgive me if this is wrong)

**Comment by abalabahaha** [comment]
It's sent as a HTTP request header
