### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by bjxke** [abalabahaha/eris#314]
I'm constantly getting this error. I found out that the stack trace shows a line from the RequestHandler, I checked it and logged the body before it was parsed to JSON. Turns out it logs 2 times for 1 message, the first message is for the message that works and the second one is the Message class.

Can anyone help? 😄

**Comment by bjxke** [comment]
Stack trace:

```js
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at actualCall (/Users/air/Documents/Adonis/node_modules/eris/lib/rest/RequestHandler.js:123:41)
    at SequentialBucket.check (/Users/air/Documents/Adonis/node_modules/eris/lib/util/SequentialBucket.js:70:28)
    at SequentialBucket.queue (/Users/air/Documents/Adonis/node_modules/eris/lib/util/SequentialBucket.js:38:14)
    at Promise (/Users/air/Documents/Adonis/node_modules/eris/lib/rest/RequestHandler.js:282:40)
    at Promise (<anonymous>)
    at RequestHandler.request (/Users/air/Documents/Adonis/node_modules/eris/lib/rest/RequestHandler.js:60:16)
    at Client.createMessage (/Users/air/Documents/Adonis/node_modules/eris/lib/Client.js:985:36)
    at GuildChannel.createMessage (/Users/air/Documents/Adonis/node_modules/eris/lib/structures/Channel.js:67:72)
    at Object.reply (/Users/air/Documents/Adonis/node_modules/eris-wiggle/lib/Command.js:53:28)
    at Object.run [as _function] (/Users/air/Documents/Adonis/node_modules/eris-wiggle/lib/Command.js:59:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by bjxke** [comment]
Heres what happens before it parses to JSON: https://aeris.takes-pictures-of.me/10ab0e.png
That Message class has the content 'Pong! `145`ms'

**Comment by bjxke** [comment]
I'm sorry it's my issue.
