### ISSUE TITLE
Errors don't have .code or .message

### ISSUE THREAD

**Issue by PassTheMayo** [abalabahaha/eris#342]
9 days ago, abal made a commit that cleaned up REST errors. I tried to use `.code` on the error, but it was `undefined`. I can still see the `.res` and `.req` properties, which means that the commit didn't work as expected. I then enabled restMode on the client and tried again, and same issue arised. Is it something I'm doing wrong? By the way, it's commit c29bbcf8dbe185535cb6efc37b2c599fa0e8cab0.

**Comment by LJNeon** [comment]
On 0.8.2 I am unable to repro this.

**Comment by PassTheMayo** [comment]
I did both `npm i eris@latest` and `npm i abalabahah/eris` to upgrade to the latest eris version.

**Comment by abalabahaha** [comment]
Where’s the error from? What does the error stack look like?

**Comment by PassTheMayo** [comment]
@abalabahaha I got the error from both `process.on("unhandledRejection" ...)` and `.catch(...)` directly on the `.createMessage()`.

**Comment by abalabahaha** [comment]
What does the error stack look like?

**Comment by PassTheMayo** [comment]
@abalabahaha I can't show right now, I'm not at home.

**Comment by macdja38** [comment]
@PassTheMayo can you drop the version of eris you have installed in this chat?
`npm view eris version`

**Comment by PassTheMayo** [comment]
@macdja38 Sure I'll try it when I get home.

**Comment by PassTheMayo** [comment]
@macdja38 I've ran that and I got `0.8.2`.

**Comment by PassTheMayo** [comment]
@abalabahaha Here's the output of an error:
```js
{"code": 50013, "message": "Missing Permissions"}
    at Gunzip._respStream.on.once (/Users/jacobgunther/Documents/Starboy/src/node_modules/eris/lib/rest/RequestHandler.js:260:39)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  resp: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: { end: [Function: responseOnEnd] },
     _eventsCount: 1,
     _maxListeners: undefined,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 810,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 4011,
        _destroyed: false,
        read: [Function],
        _consuming: true,
        [Symbol(asyncId)]: 788,
        [Symbol(bytesRead)]: 625,
        [Symbol(asyncId)]: 794,
        [Symbol(triggerAsyncId)]: 791 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 810,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 4011,
        _destroyed: false,
        read: [Function],
        _consuming: true,
        [Symbol(asyncId)]: 788,
        [Symbol(bytesRead)]: 625,
        [Symbol(asyncId)]: 794,
        [Symbol(triggerAsyncId)]: 791 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { date: 'Sat, 16 Dec 2017 02:40:30 GMT',
        'content-type': 'application/json',
        'transfer-encoding': 'chunked',
        connection: 'close',
        'set-cookie': [Array],
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'x-ratelimit-limit': '5',
        'x-ratelimit-remaining': '3',
        'x-ratelimit-reset': '1513392035',
        via: '1.1 google',
        'alt-svc': 'clear',
        server: 'cloudflare-nginx',
        'cf-ray': '3cde473ba94d5c3f-STL',
        'content-encoding': 'gzip' },
     rawHeaders: 
      [ 'Date',
        'Sat, 16 Dec 2017 02:40:30 GMT',
        'Content-Type',
        'application/json',
        'Transfer-Encoding',
        'chunked',
        'Connection',
        'close',
        'Set-Cookie',
        '__cfduid=d519b405d73bb1c06ea07408d7a2e35fa1513392030; expires=Sun, 16-Dec-18 02:40:30 GMT; path=/; domain=.discordapp.com; HttpOnly',
        'Strict-Transport-Security',
        'max-age=31536000; includeSubDomains',
        'X-RateLimit-Limit',
        '5',
        'X-RateLimit-Remaining',
        '3',
        'X-RateLimit-Reset',
        '1513392035',
        'Via',
        '1.1 google',
        'Alt-Svc',
        'clear',
        'Server',
        'cloudflare-nginx',
        'CF-RAY',
        '3cde473ba94d5c3f-STL',
        'Content-Encoding',
        'gzip' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 403,
     statusMessage: 'FORBIDDEN',
     client: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 810,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 4011,
        _destroyed: false,
        read: [Function],
        _consuming: true,
        [Symbol(asyncId)]: 788,
        [Symbol(bytesRead)]: 625,
        [Symbol(asyncId)]: 794,
        [Symbol(triggerAsyncId)]: 791 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 474,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /api/v6/channels/285084336225779722/messages HTTP/1.1\r\nUser-Agent: DiscordBot (https://github.com/abalabahaha/eris, 0.8.1)\r\nAccept-Encoding: gzip,deflate\r\nAuthorization: Bot Mzc0OTIzNjQ0MzA2MDYzMzYw.DQT0dQ.z-rQOwddfVI-pBt1alpwbi3Eul0\r\nContent-Type: application/json\r\nHost: discordapp.com\r\nConnection: close\r\nContent-Length: 474\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/v6/channels/285084336225779722/messages',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     read: [Function] },
  response: '{"code": 50013, "message": "Missing Permissions"}',
  req: 
   ClientRequest {
     domain: null,
     _events: 
      { abort: [Object],
        aborted: [Object],
        error: [Object],
        timeout: [Object],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 5,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 474,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 810,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 4011,
        _destroyed: false,
        read: [Function],
        _consuming: true,
        [Symbol(asyncId)]: 788,
        [Symbol(bytesRead)]: 625,
        [Symbol(asyncId)]: 794,
        [Symbol(triggerAsyncId)]: 791 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'discordapp.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 810,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 4011,
        _destroyed: false,
        read: [Function],
        _consuming: true,
        [Symbol(asyncId)]: 788,
        [Symbol(bytesRead)]: 625,
        [Symbol(asyncId)]: 794,
        [Symbol(triggerAsyncId)]: 791 },
     _header: 'POST /api/v6/channels/285084336225779722/messages HTTP/1.1\r\nUser-Agent: DiscordBot (https://github.com/abalabahaha/eris, 0.8.1)\r\nAccept-Encoding: gzip,deflate\r\nAuthorization: Bot Mzc0OTIzNjQ0MzA2MDYzMzYw.DQT0dQ.z-rQOwddfVI-pBt1alpwbi3Eul0\r\nContent-Type: application/json\r\nHost: discordapp.com\r\nConnection: close\r\nContent-Length: 474\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/api/v6/channels/285084336225779722/messages',
     _ended: true,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 403,
        statusMessage: 'FORBIDDEN',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        read: [Function] },
     aborted: undefined,
     timeoutCb: [Function: emitTimeout],
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     [Symbol(outHeadersKey)]: 
      { 'user-agent': [Array],
        'accept-encoding': [Array],
        authorization: [Array],
        'content-type': [Array],
        host: [Array] } } }
```

EDIT: The token in the error above is invalid, in case you're trying to steal :)

**Comment by macdja38** [comment]
how just to double check how are you logging this error?

**Comment by PassTheMayo** [comment]
@macdja38 
```js
process.on("unhandledRejection", (error) => {
	if (error.code && (error.code === 50013 || error.code === 50001 || error.code === 50007)) return;
	console.error(error);
});
```

**Comment by macdja38** [comment]
Wait... you're logging error.resp to console? That's why it has extra properties... the new error thing is on `error` do.
```js
console.log(error);
```

**Comment by PassTheMayo** [comment]
@macdja38 Oops, forgot that was there. I was just testing around, seeing how I can get the status code. I am using `console.log(error);`.

**Comment by abalabahaha** [comment]
Yeah uhh... You're missing literally everything from that commit (`/api/v7`, `.resp` renamed to `.res`, hidden `.req`/`.res`, `error.code`, flattened `error.message`, saved `error.stack`), maybe more. Also unable to reproduce on 0.8.2 here. Try doing a reinstall (`npm remove eris`, `npm install eris@0.8.2`, `npm ls eris`)

**Comment by PassTheMayo** [comment]
@abalabahaha I followed your instructions and reinstalled it, but same error occurs. Here's the full output: https://haste.passthemayo.space/adukayicur.bash

**Comment by PassTheMayo** [comment]
Aaaaaaa!!!! I found the issue! It turns out there was another `node_modules` folder another subdirectory down that had an older Eris version installed, and Node.js was using that instead. So basically there was this style of folders:
```
/
    node_modules/ # (has never version)
    src/
        index.js
        node_modules/ # being used by script (has older version)
```

**Comment by PassTheMayo** [comment]
Sorry for the confusion, a fault on my part.
