### ISSUE TITLE
Voice receive broken for reconnected voice connections

### ISSUE THREAD

**Issue by Yahweasel** [abalabahaha/eris#359]
If you connect to a voice channel in a guild, disconnect, then connect to a voice channel again (same or different), the second fails to receive any data, although showing all signs of connecting successfully. Example code:

```javascript
const fs = require("fs");
const Eris = require("eris");
const config = JSON.parse(fs.readFileSync("config.json", "utf8"));
const client = new Eris(config.token);

var counter = 0;

function session(connection) {
    const sessionNum = ++counter;
    console.log("Starting session " + sessionNum);
    const opus = connection.receive("opus");
    opus.on("data", ()=>{
        console.log(sessionNum);
    });
    connection.on("disconnect", ()=>{
        console.log("Ending session " + sessionNum);
    });
}

client.on("messageCreate", (msg) => {
    if (msg.content === "join") {
        if (msg.member && msg.channel.guild && msg.member.voiceState.channelID) {
            var channel = msg.channel.guild.channels.get(msg.member.voiceState.channelID);
            if (!channel) return;
            channel.join({opusOnly:true}).then(session).catch(console.error);
        }
    } else if (msg.content === "leave") {
        if (msg.channel.guild) {
            var vc = client.voiceConnections.get(msg.channel.guild.id);
            if (!vc) return;
            vc.disconnect(); // Should channel.leave() instead, but this is what I have :)
        }
    }
});

client.connect();
```

Expected output:
```
Starting session 1
1
1
...
Ending session 1
Starting session 2
2
2
...
Ending session 2
```

Actual output:
```
Starting session 1
1
1
...
Ending session 1
Starting session 2
Ending session 2
```

Note that I somewhat naughtily used the undocumented VoiceConnection.disconnect function instead of VoiceChannel.leave, but the result is the same either way, it was just easier in this example :)

**Comment by Yahweasel** [comment]
OK, never mind, the bug is SLIGHTLY weirder than I'd realized, as the actual output is:

```
Starting session 1
1
1
...
Ending session 1
Starting session 2
Ending session 1
Ending session 2
```

i.e., the disconnect event fires into the PREVIOUS session's callback. I assume the VoiceConnection is being reused, but it appears to be reused in a nonworking way.

**Comment by Yahweasel** [comment]
Behold, the world's cheekiest (and thus best) workaround:

```javascript
const fs = require("fs");
const Eris = require("eris");
const config = JSON.parse(fs.readFileSync("config.json", "utf8"));
const client = new Eris(config.token);

var counter = 0;

function session(connection, guild) {
    const sessionNum = ++counter;
    console.log("Starting session " + sessionNum);
    const opus = connection.receive("opus");
    opus.on("data", ()=>{
        console.log(sessionNum);
    });
    connection.on("disconnect", ()=>{
        console.log("Ending session " + sessionNum);
        client.voiceConnections.delete(guild.id);
    });
}

client.on("messageCreate", (msg) => {
    if (msg.content === "join") {
        if (msg.member && msg.channel.guild && msg.member.voiceState.channelID) {
            var channel = msg.channel.guild.channels.get(msg.member.voiceState.channelID);
            if (!channel) return;
            channel.join({opusOnly:true})
                .then((connection)=>{session(connection,msg.channel.guild);})
                .catch(console.error);
        }
    } else if (msg.content === "leave") {
        if (msg.channel.guild) {
            var me = msg.channel.guild.members.get(client.user.id);
            if (!me) return;
            var cid = me.voiceState.channelID;
            if (!cid) return;
            var channel = msg.channel.guild.channels.get(cid);
            if (!channel) return;
            channel.leave();
            /*
            var vc = client.voiceConnections.get(msg.channel.guild.id);
            if (!vc) return;
            vc.disconnect();
            */
        }
    }
});

client.connect();
```

So, yes, it has something to do with mis-reusing the voice connection. Presumably any existing VoiceConnection should universally be scrapped if you're doing a fresh join.

**Comment by abalabahaha** [comment]
Something on your end appears to have swallowed a rather useful error stacktrace
```
TypeError: this.receiveStreamOpus.destroy is not a function
    at VoiceConnection._destroy (/home/abal/Documents/eris/lib/voice/VoiceConnection.js:170:36)
    at Map.leave (/home/abal/Documents/eris/lib/voice/VoiceConnectionManager.js:113:20)
    at Client.leaveVoiceChannel (/home/abal/Documents/eris/lib/Client.js:289:31)
```
