### ISSUE TITLE
TypeError in OnMessageCreate, CommandClient.js

### ISSUE THREAD

**Issue by LynnAU** [abalabahaha/eris#362]
`TypeError: Cannot read property 'id' of undefined`
This seems to be occurring randomly or at least, I can't tell what behaviour causes this crash...

Points to line 142:58 of CommandClient.js, `msg.author.id`.
```
if((!this.commandOptions.ignoreSelf || msg.author.id !== this.user.id) && (!this.commandOptions.ignoreBots || !msg.author.bot) && (msg.prefix = this.checkPrefix(msg)))
```

Full stacktrace:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'id' of undefined
    at CommandClient.onMessageCreate (C:\Users\thoma\dev\isac-modularity\node_modules\eris\lib\command\CommandClient.js:142:58)
    at emitOne (events.js:120:20)
    at CommandClient.emit (events.js:210:7)
    at Shard.emit (C:\Users\thoma\dev\isac-modularity\node_modules\eris\lib\gateway\Shard.js:1877:26)
    at Shard.wsEvent (C:\Users\thoma\dev\isac-modularity\node_modules\eris\lib\gateway\Shard.js:418:26)
    at Shard.onWSMessage (C:\Users\thoma\dev\isac-modularity\node_modules\eris\lib\gateway\Shard.js:1716:26)
    at WebSocket.ws.onmessage (C:\Users\thoma\dev\isac-modularity\node_modules\eris\lib\gateway\Shard.js:1593:33)
    at WebSocket.onMessage (C:\Users\thoma\dev\isac-modularity\node_modules\eris\node_modules\ws\lib\EventTarget.js:99:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (C:\Users\thoma\dev\isac-modularity\node_modules\eris\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (C:\Users\thoma\dev\isac-modularity\node_modules\eris\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (C:\Users\thoma\dev\isac-modularity\node_modules\eris\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (C:\Users\thoma\dev\isac-modularity\node_modules\eris\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (C:\Users\thoma\dev\isac-modularity\node_modules\eris\node_modules\ws\lib\Receiver.js:139:10)
    at TLSSocket._ultron.on (C:\Users\thoma\dev\isac-modularity\node_modules\eris\node_modules\ws\lib\WebSocket.js:138:22)
```

**Comment by InATrance** [comment]
I get this error a lot too.

`msg.author` is undefined.
Perhaps add a checker for if msg.author is defined?
