### ISSUE TITLE
Promise Rejection Without a Reconnection?

### ISSUE THREAD

**Issue by exoRift** [abalabahaha/eris#419]
I'm not sure how to replicate, but my client lost connection with this rejection and didn't auto-reconnect.
EDIT: After some discussions, the error was on `client.connect()`. So, I don't know why it was a Forbidden error, maybe on Discord's part, but I still think it should reattempt.
```
Sep 18 04:48:12 gaijin-bot app/bot.1:  (node:20) UnhandledPromiseRejectionWarning: DiscordHTTPError: 403 Forbidden on GET /api/v7/gateway 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at RequestHandler.request (/app/node_modules/eris/lib/rest/RequestHandler.js:69:15) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at Client.getGateway (/app/node_modules/eris/lib/Client.js:218:36) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at Client.connect (/app/node_modules/eris/lib/Client.js:174:97) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at Object.<anonymous> (/app/bot.js:772:8) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at Module._compile (module.js:652:30) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at Object.Module._extensions..js (module.js:663:10) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at Module.load (module.js:565:32) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at tryModuleLoad (module.js:505:12) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at Function.Module._load (module.js:497:3) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at Function.Module.runMain (module.js:693:10) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at startup (bootstrap_node.js:191:16) 
Sep 18 04:48:12 gaijin-bot app/bot.1:      at bootstrap_node.js:612:3 
Sep 18 04:48:12 gaijin-bot app/bot.1:  (node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)  
Sep 18 04:48:12 gaijin-bot app/bot.1:  (node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TheOnlyArtz** [comment]
Hey, You didn't lose your connection your tried to do an operation that you bot can't do because lack of permissions

**Comment by exoRift** [comment]
No, it would show a custom rejection on that, and yes, it DID lose connection because my bot was offline. I had to restart. Promise rejections don't crash the process. This was a failure at connection/pinging the API.

**Comment by abalabahaha** [comment]
403 on /gateway usually means you got IP banned or token reset. Shouldn’t be auto reconnecting in either case.
