### ISSUE TITLE
autoreconnect never reconnects if internet drops

### ISSUE THREAD

**Issue by Ovyerus** [abalabahaha/eris#431]
If the internet dies when a bot is connected to Discord, it throws an error and (seemingly) never tries to reconnect to Discord, and also seems to not cause the program to exit, essentially hanging the script.

```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at SaladBot.emit (events.js:171:17)
    at SaladBot.EventEmitter.emit (domain.js:442:20)
    at SaladBot.emit (/home/moo/saladbot/node_modules/erisa/dist/src/Erisa.js:143:22)
    at Shard.emit (/home/moo/saladbot/node_modules/eris/lib/gateway/Shard.js:1882:26)
    at WebSocket.ws.onerror (/home/moo/saladbot/node_modules/eris/lib/gateway/Shard.js:1605:18)
    at WebSocket.onError (/home/moo/saladbot/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.EventEmitter.emit (domain.js:442:20)
    at ClientRequest.req.on (/home/moo/saladbot/node_modules/ws/lib/websocket.js:535:10)
    at ClientRequest.emit (events.js:182:13)
Error: connect ENETUNREACH 172.250.250.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```

**Comment by abalabahaha** [comment]
> ERR_UNHANDLED_ERROR
Try handling the "error" event. If the program is not exiting, something higher in the program is preventing it from exiting on unhandled error events (default Node behavior).

Feel free to re-open if you have narrowed this down to be a library issue with consistent reproduction steps (barebones script).
