### ISSUE TITLE
Warning: a promise was rejected with a non-error

### ISSUE THREAD

**Issue by PassTheMayo** [abalabahaha/eris#535]
Since some recent Node.js version, Node will now emit warnings if you reject a Promise with a non-`Error` type. Some things in Eris aren't rejected with errors, such as `Client#getInvite()`. I don't know of any other ones, but I'd assume there is more. Any ETA on a fix? This is currently filling up my logs, and I'd really like to stay away from `--no-warnings`.

After digging some more, I found something odd...
`(node:3317) Warning: a promise was rejected with a non-error: [object Error]`

**Comment by alex-taxiera** [comment]
What version of node are you getting this with?

**Comment by PassTheMayo** [comment]
@alex-taxiera I'm using Node v12.4.0. I know there is an update, but I'd assume it's the same issue.

**Comment by alex-taxiera** [comment]
@PassTheMayo Can you provide repro steps? I have tried to reproduce this on node 12.4.0 with `Client#getInvite` to no avail.

Here's what I tried:

```js
const client = new require('eris')(token)

client.on('ready', async () => {
  await client.getInvite('zzz')
  console.log('done')
});
```
Whether the ID passed to `getInvite` is valid or not I do not get this error. I tried both stable and dev.

**Comment by abalabahaha** [comment]
This is an error caused not by Node 12, but [by `bluebird`](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-rejected-with-a-non-error), which I believe lets you turn off warnings in production by setting `NODE_ENV` properly.

Can you grab the stacktrace for one of these "errors"?

**Comment by PassTheMayo** [comment]
@abalabahaha Ah, that probably makes sense, I do override my global's Promise value with bluebird. I could of swore that this was created from the normal Promises. Though, the stacktrace showed no hint of bluebird so I assumed it was Node. Sadly I can't get a stacktrace because I had cleared my PM2 logs shortly after. I still think this should be looked into, and identify what is causing it.

**Comment by abalabahaha** [comment]
Yeah, stacktrace would help with identifying that

**Comment by PassTheMayo** [comment]
@abalabahaha @alex-taxiera I have reproduced the error myself using an invalid invite code and configuring bluebird to show all errors.
Here's the full stack trace:
```js
(node:2696) Warning: a promise was rejected with a non-error: [object Error]
    at IncomingMessage.<anonymous> (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\rest\RequestHandler.js:285:29)     
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1161:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
From previous event:
    at RequestHandler.request (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\rest\RequestHandler.js:72:16)
    at Client.getInvite (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\Client.js:878:36)
    at Client.<anonymous> (C:\Users\jacob\Documents\Testing\test-eris-bug\index.js:14:9)
    at Client.emit (events.js:203:13)
    at Shard.<anonymous> (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\gateway\ShardManager.js:71:30)
    at Shard.emit (events.js:203:13)
    at Shard.checkReady (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\gateway\Shard.js:1562:23)
    at Shard.wsEvent (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\gateway\Shard.js:1319:26)
    at Shard.onWSMessage (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\gateway\Shard.js:1767:26)
    at WebSocket.ws.onmessage (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\gateway\Shard.js:1645:33)
    at WebSocket.onMessage (C:\Users\jacob\Documents\Testing\node_modules\eris\node_modules\ws\lib\event-target.js:120:16)    
    at WebSocket.emit (events.js:203:13)
    at Receiver.receiverOnMessage (C:\Users\jacob\Documents\Testing\node_modules\eris\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:203:13)
    at Receiver.dataMessage (C:\Users\jacob\Documents\Testing\node_modules\eris\node_modules\ws\lib\receiver.js:422:14)       
    at Receiver.getData (C:\Users\jacob\Documents\Testing\node_modules\eris\node_modules\ws\lib\receiver.js:352:17)
    at Receiver.startLoop (C:\Users\jacob\Documents\Testing\node_modules\eris\node_modules\ws\lib\receiver.js:138:22)
    at Receiver._write (C:\Users\jacob\Documents\Testing\node_modules\eris\node_modules\ws\lib\receiver.js:74:10)
    at doWrite (_stream_writable.js:417:12)
DiscordRESTError [10006]: Unknown Invite
    at RequestHandler.request (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\rest\RequestHandler.js:70:15)
    at Client.getInvite (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\Client.js:878:36)
    at Client.<anonymous> (C:\Users\jacob\Documents\Testing\test-eris-bug\index.js:14:9)
    at Client.emit (events.js:203:13)
    at Shard.<anonymous> (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\gateway\ShardManager.js:71:30)
    at Shard.emit (events.js:203:13)
    at Shard.checkReady (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\gateway\Shard.js:1562:23)
    at Shard.wsEvent (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\gateway\Shard.js:1319:26)
    at Shard.onWSMessage (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\gateway\Shard.js:1767:26)
    at WebSocket.ws.onmessage (C:\Users\jacob\Documents\Testing\node_modules\eris\lib\gateway\Shard.js:1645:33)
    at WebSocket.onMessage (C:\Users\jacob\Documents\Testing\node_modules\eris\node_modules\ws\lib\event-target.js:120:16)    
    at WebSocket.emit (events.js:203:13)
    at Receiver.receiverOnMessage (C:\Users\jacob\Documents\Testing\node_modules\eris\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:203:13)
    at Receiver.dataMessage (C:\Users\jacob\Documents\Testing\node_modules\eris\node_modules\ws\lib\receiver.js:422:14)       
    at Receiver.getData (C:\Users\jacob\Documents\Testing\node_modules\eris\node_modules\ws\lib\receiver.js:352:17)
```

Here's the code:
```js
const Eris = require('eris');
const bluebird = require('bluebird');

bluebird.config({
	longStackTraces: true,
	warnings: true
});

global.Promise = bluebird;

const client = new Eris.Client('xxx');

client.on('ready', () => {
	client.getInvite('fgfggdfsgfgfdgdfggdfg', true)
		.then(() => {
			console.log('Got invite!');
		})
		.catch((error) => {
			console.error(error);
		});
});

client.connect();
```

Hope this helps!

**Comment by alex-taxiera** [comment]
It seems like Bluebird likes to tell custom Error objects to sod off. I have found that it is complaining because we redefine the `stack` property as unwritable. Simply commenting out [this line](https://github.com/abalabahaha/eris/blob/master/lib/errors/DiscordRESTError.js#L45) makes it work without that warning.
