### ISSUE TITLE
TextChannel.purge: Unknown Message

### ISSUE THREAD

**Issue by Sei4or** [abalabahaha/eris#659]
Currently, there seems to be a bug with the purge method when providing a filter and a limit.
Not sure what is causing this error.

DiscordRESTError [10008]: Unknown Message
    at RequestHandler.request (...node_modules\eris\lib\rest\RequestHandler.js:71:15)
    at Client.deleteMessage (...node_modules\eris\lib\Client.js:1170:36)
    at Client.deleteMessages (...node_modules\eris\lib\Client.js:1187:25)
    at checkToDelete (...node_modules\eris\lib\Client.js:1231:28)
    at Client.purgeChannel (...node_modules\eris\lib\Client.js:1272:16)

Version: 0.11.2

**Comment by eritbh** [comment]
This probably isn't a bug, but we need more information about how to reproduce this in order to check it out.

**Comment by Sei4or** [comment]
This issue was caused by a race condition as I was deleting a message right before purging. Not a bug with the library.
