### ISSUE TITLE
opusscript is required

### ISSUE THREAD

**Issue by nandub** [abalabahaha/eris#83]
Per the package.json `opusscript` is optional however when using eris 0.3.0 you get the error below:

```
1:14:47 PM web.1 |  module.js:442
1:14:47 PM web.1 |      throw err;
1:14:47 PM web.1 |      ^
1:14:47 PM web.1 |  Error: Cannot find module 'opusscript'
1:14:47 PM web.1 |      at Function.Module._resolveFilename (module.js:440:15)
1:14:47 PM web.1 |      at Function.Module._load (module.js:388:25)
1:14:47 PM web.1 |      at Module.require (module.js:468:17)
1:14:47 PM web.1 |      at require (internal/module.js:20:19)
1:14:47 PM web.1 |      at Object.<anonymous> (/Users/nandub/development/source/discord-webhook/node_modules/eris/lib/voice/VoiceConnection.js:10:20)
1:14:47 PM web.1 |      at Module._compile (module.js:541:32)
1:14:47 PM web.1 |      at Object.Module._extensions..js (module.js:550:10)
1:14:47 PM web.1 |      at Module.load (module.js:458:32)
1:14:47 PM web.1 |      at tryModuleLoad (module.js:417:12)
1:14:47 PM web.1 |      at Function.Module._load (module.js:409:3)
1:14:47 PM web.1 |  module.js:442
1:14:47 PM web.1 |      throw err;
```

**Comment by nandub** [comment]
I like the `abal's code sucks` label, but don't agree with it. :)

**Comment by abalabahaha** [comment]
Fixed in dev branch
