### ISSUE TITLE
Supported opus encoder not found

### ISSUE THREAD

**Issue by seia-soto** [abalabahaha/eris#928]
## Environment

- Tested platforms: Ubuntu Server 18.04.3 LTS x64-aws, **Windows 10 1909 (Build 18363.815)**
- Visual Studio 14.3 (2015 with update 3)
- Node.JS v10 (v10.21.0) installed via NVM-Windows
- FFmpeg v4.2.2 stable (ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122)

### Depedencies

The following items are the dependencies that can affect the result.

```json
{
"bufferutil": "^4.0.1",
"eris": "^0.11.2",
"erlpack": "abalabahaha/erlpack",
"eventemitter3": "^4.0.0",
"node-fetch": "^2.6.0",
"node-opus": "^0.3.3",
"zlib-sync": "^0.1.6"
}
```

### FFmpeg raw output

```
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

## Problem

The package `node-opus` is deprecated and I am not sure if it is working well. However, I am sure that the package will work correctly even the package was deprecated since the code is same.

```
Error: Supported opus encoder not found
    at new PCMOpusTransformer (D:\Library\Repositories\PROJECT\node_modules\eris\lib\voice\streams\PCMOpusTransformer.js:8:19)
    at Piper.encode (D:\Library\Repositories\PROJECT\node_modules\eris\lib\voice\Piper.js:113:52)
    at VoiceConnection.play (D:\Library\Repositories\PROJECT\node_modules\eris\lib\voice\VoiceConnection.js:444:24)
    at Object.fn (SOURCE)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Code

When I try to execute the following code line (`VoiceConnection.play`), the error occurs.

```js
connection.play(featuredSoundStream, {
  inlineVolume: true
})
connection.setVolume(0.7)
```

- `featuredSoundStream`: `ReadableStream` via `fs.createReadStream`

**Comment by abalabahaha** [comment]
Please confirm that this still happens on 0.12.0

**Comment by seia-soto** [comment]
✔️ After updating Eris.JS to 0.12.0, the error disappeared. Thank you for confirming. All other environments are same. 

```json
{
  "eris": "^0.12.0"
}
```
