### ISSUE TITLE
Streams are getting destroyed 

### ISSUE THREAD

**Issue by thrace19** [abalabahaha/eris#929]
```js
events.js:173
      throw er; // Unhandled 'error' event
      ^
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:413:19)
    at writeOrBuffer (_stream_writable.js:401:5)
    at WebmOpusTransformer.Writable.write (_stream_writable.js:301:11)
    at PassThrough.ondata (_stream_readable.js:696:22)
    at PassThrough.emit (events.js:196:13)
    at PassThrough.Readable.read (_stream_readable.js:491:10)
    at flow (_stream_readable.js:960:34)
    at WebmOpusTransformer.pipeOnDrainFunctionResult (_stream_readable.js:764:7)
    at WebmOpusTransformer.emit (events.js:196:13)
    at onwriteDrain (_stream_writable.js:493:12)
Emitted 'error' event at:
    at Piper.<anonymous> (/rbd/pnpm-volume/dc35159f-ad7b-41e0-ac9a-f6afff1ae8a6/node_modules/.registry.npmjs.org/eris/0.12.0/node_modules/eris/lib/voice/VoiceConnection.js:131:48)
    at Piper.emit (events.js:196:13)
    at Piper.stop (/rbd/pnpm-volume/dc35159f-ad7b-41e0-ac9a-f6afff1ae8a6/node_modules/.registry.npmjs.org/eris/0.12.0/node_modules/eris/lib/voice/Piper.js:188:18)
    at WebmOpusTransformer.<anonymous> (/rbd/pnpm-volume/dc35159f-ad7b-41e0-ac9a-f6afff1ae8a6/node_modules/.registry.npmjs.org/eris/0.12.0/node_modules/eris/lib/voice/Piper.js:91:96)
    at Object.onceWrapper (events.js:284:20)
    at WebmOpusTransformer.emit (events.js:201:15)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:432:5)
    at onwrite (_stream_writable.js:459:5)
    at doWrite (_stream_writable.js:413:11)
``` 
from many days I'm getting this error I'm confused from which version that started and I'm on eris 0.12.0

**Comment by abalabahaha** [comment]
> // Unhandled 'error' event

You should be handling the error event, emitted from VoiceConnection in this case.

Do you have any more details? When does this happen? How often? What is the audio source? How does one reproduce this?

**Comment by thrace19** [comment]
When someone plays a song it throws that but not on all songs only some songs, the audio source is from youtube. Thanks for looking into it abal

**Comment by abalabahaha** [comment]
When you say from YouTube, how exactly are you getting the audio data? This sounds like something `ytdl-core` would throw

**Comment by thrace19** [comment]
yeah, I use ytdl-core the latest version

**Comment by thrace19** [comment]
One new error abal

```js
events.js:173
      throw er; // Unhandled 'error' event
      ^
Error: 4014: Disconnected.
    at WebSocket.<anonymous> (/rbd/pnpm-volume/6ce97dae-bf15-4cc5-a30a-23cb77c5451d/node_modules/.registry.npmjs.org/eris/0.12.0/node_modules/eris/lib/voice/VoiceConnection.js:340:57)
    at WebSocket.emit (events.js:196:13)
    at WebSocket.emitClose (/rbd/pnpm-volume/6ce97dae-bf15-4cc5-a30a-23cb77c5451d/node_modules/.registry.npmjs.org/ws/7.2.5/node_modules/ws/lib/websocket.js:194:10)
    at TLSSocket.socketOnClose (/rbd/pnpm-volume/6ce97dae-bf15-4cc5-a30a-23cb77c5451d/node_modules/.registry.npmjs.org/ws/7.2.5/node_modules/ws/lib/websocket.js:861:15)
    at TLSSocket.emit (events.js:201:15)
    at net.js:586:12
    at TCP.done (_tls_wrap.js:445:7)
Emitted 'error' event at:
    at VoiceConnection.disconnect (/rbd/pnpm-volume/6ce97dae-bf15-4cc5-a30a-23cb77c5451d/node_modules/.registry.npmjs.org/eris/0.12.0/node_modules/eris/lib/voice/VoiceConnection.js:393:22)
    at WebSocket.<anonymous> (/rbd/pnpm-volume/6ce97dae-bf15-4cc5-a30a-23cb77c5451d/node_modules/.registry.npmjs.org/eris/0.12.0/node_modules/eris/lib/voice/VoiceConnection.js:349:22)
    at WebSocket.emit (events.js:196:13)
    [... lines matching original stack trace ...]
    at TCP.done (_tls_wrap.js:445:7)
```

**Comment by abalabahaha** [comment]
Neither of these looks like an Eris problem. The ytdl streaming function has historically been problematic, it may be better to use it to get the download URL and pass that to Eris. Voice close code 4014 is already documented on Discord's docs as being kicked from the channel for some reason, and your code should be able to handle situations like this depending on what you want to do. You can visit the Discord channel if you still have questions about this.
