### ISSUE TITLE
Banning guild members crashes bot

### ISSUE THREAD

**Issue by Ratismal** [abalabahaha/eris#99]
Hi,

Whenever I ban a user on the latest dev build, my bot crashes with this error:

``` js
path\to\node_modules\eris\lib\rest\RequestHandler.js:122
                    this.ratelimits[url].latency = latency;
                                                 ^

TypeError: Cannot set property 'latency' of undefined
    at IncomingMessage.__dirname.request.req.once.resp.once.err (path\to\node_modules\eris\lib\rest\RequestHandler.js:122:50)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any fix would be greatly appreciated.

**Comment by hsiW** [comment]
Fixed in https://github.com/abalabahaha/eris/commit/585ba8c0ab4831fba5aa65cda4e1cf9780685390
