### ISSUE TITLE
TypeError: this.ws.removeEventListener is not a function

### ISSUE THREAD

**Issue by Malathub** [abalabahaha/eris#992]
I have a problem when I launch my bot

```
/root/Bot/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:99
0|npm  |             this.ws.removeEventListener("close", this._onWSClose);
0|npm  |                     ^
0|npm  | TypeError: this.ws.removeEventListener is not a function
0|npm  |     at Shard.disconnect (/root/Bot/invite-manager-bot/node_modules/eris                                                                                                               /lib/gateway/Shard.js:99:21)
0|npm  |     at Shard.heartbeat (/root/Bot/invite-manager-bot/node_modules/eris/                                                                                                               lib/gateway/Shard.js:2001:29)
0|npm  |     at Timeout.heartbeatInterval.setInterval (/root/Bot/invite-manager-                                                                                                               bot/node_modules/eris/lib/gateway/Shard.js:1948:69)
0|npm  |     at ontimeout (timers.js:436:11)
0|npm  |     at tryOnTimeout (timers.js:300:5)
0|npm  |     at listOnTimeout (timers.js:263:5)
0|npm  |     at Timer.processTimers (timers.js:223:10)

```

**Comment by abalabahaha** [comment]
Seems to have been a corrupted install of `ws`, clearing `node_modules` and reinstalling everything fixed this.

**Comment by AndreasGassmann** [comment]
I had the same issue yesterday, but clearing the `node_modules` folder didn't help. `pm2` kept restarting the process and the error happened after about 30 seconds. I left it running and it crashed repeatedly, but then at some point it just randomly stopped. Just like it randomly started because that process was running for weeks without any issues.

I'm not sure what it is though. Might be related to the connection?
